# Generated by Django 4.2.7 on 2023-12-15 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="status",),
    ]
