# Generated by Django 4.2.7 on 2023-11-17 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("profile_picture", models.ImageField(upload_to="library_profiles/")),
                ("header_image", models.ImageField(upload_to="library_profiles/")),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                ("faqs", models.TextField(help_text="Frequently Asked Questions")),
                ("contact", models.TextField(help_text="Contact Information")),
                ("opening_hours", models.CharField(blank=True, max_length=255)),
                ("website_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("accessibility_info", models.TextField(blank=True)),
                ("membership_info", models.TextField(blank=True)),
                ("catalog_link", models.URLField(blank=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("unique_features", models.TextField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("collection_size", models.IntegerField(blank=True, null=True)),
                ("languages_supported", models.CharField(blank=True, max_length=255)),
                ("public_transport_links", models.TextField(blank=True)),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followed_libraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
