# Generated by Django 4.2.7 on 2023-12-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0003_alter_libraryprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryprofile",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="libraryprofile",
            name="contact",
            field=models.TextField(help_text="Contact Information"),
        ),
        migrations.AlterField(
            model_name="libraryprofile", name="description", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="libraryprofile",
            name="faqs",
            field=models.TextField(help_text="Frequently Asked Questions"),
        ),
        migrations.AlterField(
            model_name="libraryprofile",
            name="header_image",
            field=models.ImageField(upload_to="library_profiles/"),
        ),
        migrations.AlterField(
            model_name="libraryprofile",
            name="profile_picture",
            field=models.ImageField(upload_to="library_profiles/"),
        ),
        migrations.AlterField(
            model_name="libraryprofile",
            name="state",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="libraryprofile",
            name="street_address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="libraryprofile",
            name="zip_code",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(name="LibraryVisit",),
    ]
