# Generated by Django 4.2.7 on 2023-12-15 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=255, null=True)),
                ("Brand", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.IntegerField(blank=True, default=1, null=True)),
                ("serial", models.CharField(max_length=1000, null=True)),
                ("assettag", models.CharField(blank=True, max_length=255, null=True)),
                ("ShortDescription", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("components", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("n", "New"),
                            ("g", "Good"),
                            ("u", "Used"),
                            ("b", "Broken"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "pricepaid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=100, null=True
                    ),
                ),
                ("care", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/assets/<int:asset_id>"
                    ),
                ),
                (
                    "StreetAddress",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("City", models.CharField(blank=True, max_length=50, null=True)),
                ("State", models.CharField(blank=True, max_length=50, null=True)),
                ("areacode", models.IntegerField(blank=True, null=True)),
                ("checkedout", models.BooleanField(default=False)),
                ("Requested", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_out_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("libraries", models.ManyToManyField(to="libraries.libraryprofile")),
                (
                    "requested_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="requested_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_requested",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="inventory.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Request",
                "verbose_name_plural": "Asset Requests",
            },
        ),
    ]
