# Generated by Django 4.2.7 on 2023-11-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=255, null=True)),
                ("Brand", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.IntegerField(blank=True, default=1, null=True)),
                ("serial", models.CharField(max_length=1000, null=True)),
                ("assettag", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("components", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("n", "New"),
                            ("g", "Good"),
                            ("u", "Used"),
                            ("b", "Broken"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "pricepaid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=100, null=True
                    ),
                ),
                ("care", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/images/"
                    ),
                ),
                (
                    "StreetAddress",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("City", models.CharField(blank=True, max_length=50, null=True)),
                ("State", models.CharField(blank=True, max_length=50, null=True)),
                ("areacode", models.IntegerField(blank=True, null=True)),
                ("checkedout", models.BooleanField(blank=True, default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("libraries", models.ManyToManyField(to="libraries.libraryprofile")),
            ],
        ),
    ]
