# Generated by Django 4.2.7 on 2023-12-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/assets/"),
        ),
    ]
