# Generated by Django 4.2.7 on 2023-11-20 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0003_alter_asset_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="checked_out_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checked_out_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="requested_by",
            field=models.ManyToManyField(
                blank=True, related_name="requested_assets", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="checkedout",
            field=models.BooleanField(default=False),
        ),
    ]
