# Generated by Django 4.2.7 on 2023-12-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_asset_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="asset", name="Requested",),
        migrations.RemoveField(model_name="asset", name="ShortDescription",),
        migrations.AlterField(
            model_name="asset",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.DeleteModel(name="AssetRequest",),
    ]
